const ref = {
  user: document.querySelector('.user-button'),
  container: document.querySelector('.container'),
  favorites: document.querySelector('.favorite'),
  posts: document.querySelector('.posts'),
  addCard: document.querySelector('.add-post'),
  closeModalBtn: document.querySelector('.close-btn'),
  modalContent: document.querySelector('.modal__content'),
  adForm: document.querySelector('.ad-form'),
  formInputs: document.querySelector('.note-editor'),
  fileInput: document.querySelector('.input-file'),
  userBtn: document.querySelector('.user-button'),
  addPostBtn: document.querySelector('.add-post'),
  loginBtn: document.querySelector('.login_button'),
  logoutBtn: document.querySelector('.logout_button'),
  formDisplay: document.querySelector('.form_display'),
  openLoginFormBtn: document.querySelector('.open_login_form_btn'),
  openRegistrationFormBtn: document.querySelector('.open_registration_form_btn'),
  registrationForm: document.querySelector('.registration_form'),
  loginForm: document.querySelector('.login_form'),
  userName: document.querySelector('.user-name'),
  nextPage: document.querySelector('.next'),
  adsContainer: document.querySelector('.cotainer_allCategory'),
  search: document.querySelector("#search"),
  searchForm: document.querySelector("#searchForm"),
}

  export default ref;